/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gtTDj5VYMDK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function FeaturedProducts({ className }) {
  return (
    <section
      key="1"
      className={`${className} py-12 px-2 md:py-16 lg:py-20 dark:bg-gray-800`}
    >
      <div className="container mx-auto px-4 md:px-6">
        <div className="mb-8 md:mb-12 lg:mb-16">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-2">
            Featured Products
          </h2>
          <p className="text-gray-500 dark:text-gray-400 text-base md:text-lg">
            Discover our top-selling products for your home and lifestyle.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 md:gap-8">
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <img
              alt="Product 1"
              className="w-full h-48 object-cover"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold mb-2">Cozy Armchair</h3>
              <p className="text-gray-500 dark:text-gray-400 mb-4">
                Sink into comfort with our plush armchair.
              </p>
              <Button className="w-full">
                <ShoppingCartIcon className="mr-2 h-4 w-4" />
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <img
              alt="Product 2"
              className="w-full h-48 object-cover"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold mb-2">Modern Desk Lamp</h3>
              <p className="text-gray-500 dark:text-gray-400 mb-4">
                Illuminate your workspace with this sleek desk lamp.
              </p>
              <Button className="w-full">
                <ShoppingCartIcon className="mr-2 h-4 w-4" />
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <img
              alt="Product 3"
              className="w-full h-48 object-cover"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold mb-2">Minimalist Vase</h3>
              <p className="text-gray-500 dark:text-gray-400 mb-4">
                Add a touch of elegance to any room with this modern vase.
              </p>
              <Button className="w-full">
                <ShoppingCartIcon className="mr-2 h-4 w-4" />
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg overflow-hidden shadow-lg dark:bg-gray-950">
            <img
              alt="Product 4"
              className="w-full h-48 object-cover"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="p-4">
              <h3 className="text-lg font-semibold mb-2">Wooden Bookshelf</h3>
              <p className="text-gray-500 dark:text-gray-400 mb-4">
                Organize your books and decor with this sturdy bookshelf.
              </p>
              <Button className="w-full">
                <ShoppingCartIcon className="mr-2 h-4 w-4" />
                Add to Cart
              </Button>
            </div>
          </div>
        </div>
        <div className="mt-8 md:mt-12 lg:mt-16 text-center">
          <Button size="lg" variant="outline" asChild>
            <Link href="/products">View All</Link>
            {/* View All */}
          </Button>
        </div>
      </div>
    </section>
  );
}

function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}
