/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WYorILK6Cga
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function Footer({ categories }) {
  return (
    <footer className="bg-gray-100 dark:bg-gray-800 pt-12 pb-6 md:pt-16 md:pb-8 px-2">
      <div className="container max-w-8xl grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-12">
        <div className="space-y-4">
          <Link
            className="flex items-center gap-2 font-semibold text-gray-900 dark:text-gray-50"
            href="#"
          >
            <span>Raichur Hardware</span>
          </Link>
          <p className="text-gray-500 dark:text-gray-400">
            Raichur hardware Store is your one-stop shop for high-quality
            products at affordable prices. Discover the best deals and enjoy a
            seamless shopping experience.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-4 md:gap-14">
          <div className="space-y-2">
            <h4 className="font-semibold text-gray-900 dark:text-gray-50">
              Categories
            </h4>
            <ul className="space-y-1">
              <li>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href={`/category/all`}
                >
                  All Products
                </Link>
              </li>
              {categories &&
                categories
                  .filter((category) => category?.categoryName != "all")
                  .map((category) => (
                    <li>
                      <Link
                        className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50 capitalize"
                        href={`/category/${category?.categoryName}`}
                      >
                        {category?.categoryName}
                      </Link>
                    </li>
                  ))}
            </ul>
          </div>
          <div className="space-y-2">
            <h4 className="font-semibold text-gray-900 dark:text-gray-50">
              Quick Links
            </h4>
            <ul className="space-y-1">
              <li>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="/about"
                >
                  About Us
                </Link>
              </li>
              <li>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="/contact"
                >
                  Contact
                </Link>
              </li>
              <li>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="/faq"
                >
                  FAQs
                </Link>
              </li>
              {/* <li>
                <Link
                  className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                  href="#"
                >
                  Shipping & Returns
                </Link>
              </li> */}
            </ul>
          </div>
        </div>
        <div className="space-y-2">
          <h4 className="font-semibold text-gray-900 dark:text-gray-50">
            About
          </h4>
          <ul className="space-y-1">
            <li>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Privacy Policy
              </Link>
            </li>
            <li>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Terms of Service
              </Link>
            </li>
          </ul>
        </div>
      </div>
      <div className="container max-w-8xl mt-8 md:mt-12 flex items-center justify-between">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          ©{new Date().getFullYear()} Raichur hardware Store. All rights
          reserved.
        </p>
      </div>
    </footer>
  );
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
