/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mizehbSu4t5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";

import globalData from "@/app/data";

export function HeroTestimonials() {
  return (
    <section className="relative bg-gradient-to-b from-gray-100 to-gray-200 py-12 md:py-20 dark:from-gray-800 dark:to-gray-900">
      <div className="absolute inset-0 bg-gradient-to-tr from-gray-100/50 to-gray-200/50 opacity-50 dark:from-gray-800/50 dark:to-gray-900/50" />
      <div className="container relative px-4 md:px-6">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            What Our Customers Say
          </h2>
          <p className="mt-4 text-gray-500 dark:text-gray-400 md:text-xl">
            Hear from real people who love our products.
          </p>
        </div>
        <div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {globalData?.heroTestimonials &&
            globalData.heroTestimonials.map((testimonial, index) => (
              <div
                key={index}
                className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950"
              >
                <div className="flex items-start">
                  <Avatar className="mr-4 h-12 w-12">
                    <AvatarImage
                      alt={testimonial.name}
                      src={testimonial.image}
                    />
                    <AvatarFallback>
                      {testimonial.name[0] + testimonial.name[1]}
                    </AvatarFallback>
                  </Avatar>
                  <div>
                    <h3 className="text-lg font-semibold">
                      {testimonial.name}
                    </h3>
                    <p className="mt-2 text-gray-500 dark:text-gray-400">
                      "{testimonial.message}"
                    </p>
                  </div>
                </div>
              </div>
            ))}
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <div className="flex items-start">
              <Avatar className="mr-4 h-12 w-12">
                <AvatarImage
                  alt="Sarah Johnson"
                  src="/placeholder-avatar.jpg"
                />
                <AvatarFallback>SJ</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Sarah Johnson</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  "I absolutely love this product! It has transformed my daily
                  routine and made my life so much easier."
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <div className="flex items-start">
              <Avatar className="mr-4 h-12 w-12">
                <AvatarImage alt="Alex Smith" src="/placeholder-avatar.jpg" />
                <AvatarFallback>AS</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Alex Smith</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  "I was hesitant at first, but this product has exceeded all my
                  expectations. It's a game-changer!"
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <div className="flex items-start">
              <Avatar className="mr-4 h-12 w-12">
                <AvatarImage alt="Emily Parker" src="/placeholder-avatar.jpg" />
                <AvatarFallback>EP</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Emily Parker</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  "I've been using this product for months and I can't imagine
                  my life without it. It's truly a lifesaver!"
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <div className="flex items-start">
              <Avatar className="mr-4 h-12 w-12">
                <AvatarImage
                  alt="Michael Davis"
                  src="/placeholder-avatar.jpg"
                />
                <AvatarFallback>MD</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Michael Davis</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  "This product has truly changed the way I approach my daily
                  tasks. I highly recommend it to anyone!"
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <div className="flex items-start">
              <Avatar className="mr-4 h-12 w-12">
                <AvatarImage alt="Jessica Lee" src="/placeholder-avatar.jpg" />
                <AvatarFallback>JL</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">Jessica Lee</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  "This product has completely transformed the way I work. It's
                  been a game-changer for my productivity!"
                </p>
              </div>
            </div>
          </div>
          <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950">
            <div className="flex items-start">
              <Avatar className="mr-4 h-12 w-12">
                <AvatarImage alt="David Chen" src="/placeholder-avatar.jpg" />
                <AvatarFallback>DC</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">David Chen</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  "I was skeptical at first, but this product has exceeded all
                  my expectations. It's become an essential part of my daily
                  routine."
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
