/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mizehbSu4t5
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";

import globalData from "@/app/data";
import Image from "next/image";

export function HeroTestimonials() {
  return (
    <section className="relative bg-gradient-to-b from-gray-100 to-gray-200 py-12 md:py-20 dark:from-gray-800 dark:to-gray-900">
      <div className="absolute inset-0 bg-gradient-to-tr from-gray-100/50 to-gray-200/50 opacity-50 dark:from-gray-800/50 dark:to-gray-900/50" />
      <div className="container relative px-4 md:px-6">
        <div className="mx-auto max-w-2xl text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            What Our Customers Say
          </h2>
          <p className="mt-4 text-gray-500 dark:text-gray-400 md:text-xl">
            Hear from real people who love our products.
          </p>
        </div>

        <div className="container py-12 md:py-24">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {globalData?.heroTestimonials &&
              globalData.heroTestimonials.map((testimonial, index) => (
                <div
                  key={index}
                  className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-950"
                >
                  <div className="relative h-48 md:h-64">
                    <Image
                      src={testimonial?.image || "/placeholder.svg"}
                      alt="Testimonial 1"
                      width={640}
                      height={480}
                      className="object-cover w-full h-full"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-gray-900/50 to-transparent" />
                    <div className="absolute bottom-4 left-4 text-white">
                      <h3 className="text-lg font-semibold">
                        {testimonial?.name}
                      </h3>
                      <p className="text-sm">{testimonial?.designation}</p>
                    </div>
                  </div>
                  <div className="p-6">
                    <p className="text-gray-500 dark:text-gray-400">
                      "{testimonial?.message}"
                    </p>
                  </div>
                </div>
              ))}
          </div>
        </div>
      </div>
    </section>
  );
}
