/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OBGUzPAWg2b
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuRadioItem,
  DropdownMenuRadioGroup,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import FilterSheet from "../FilterSheet";
import FilterForm from "../FilterForm";
import Link from "next/link";

export function ProductsPage() {
  return (
    <div
      key="1"
      className="grid grid-cols-1 lg:grid-cols-[200px_1fr] gap-8 p-4 md:p-8"
    >
      <div className="hidden lg:block">
        <FilterForm showOnMobile={false} />
      </div>
      <div>
        <div className="flex items-center justify-between w-full mb-4">
          <h2 className="text-2xl font-bold">Products</h2>
          <div className="flex gap-2">
            <FilterSheet showOnMobile={true} />
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="shrink-0" variant="outline">
                  <ArrowUpDownIcon className="w-4 h-4 mr-2" />
                  Sort by
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-[200px]">
                <DropdownMenuRadioGroup value="featured">
                  <DropdownMenuRadioItem value="featured">
                    Featured
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="Newest">
                    Newest
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="low">
                    Price: Low to High
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="high">
                    Price: High to Low
                  </DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <Link href="/product/1" className="text-lg font-semibold">
                Product Name
              </Link>
              <p className="text-gray-500 dark:text-gray-400">$49.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$99.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$79.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$59.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$39.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$29.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$19.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-gray-950 dark:border dark:border-gray-800">
            <img
              alt="Product Image"
              className="w-full h-48 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <div className="p-4 space-y-2">
              <h3 className="text-lg font-semibold">Product Name</h3>
              <p className="text-gray-500 dark:text-gray-400">$14.99</p>
              <Button className="w-full" size="sm">
                Add to Cart
              </Button>
            </div>
          </div>
        </div>
        <Button className="w-full mx-auto mt-10" variant="outline">
          Load More Products
        </Button>
      </div>
    </div>
  );
}

function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
